Card teacher
javonunezz/teacher_book_front pull request #8
Opened 2023-05-14 22:15 UTC by javonunezz

### Context
In order to display the teacher's information on the website, an information card was needed as well as a home page where this card could be displayed.

### What did I do?
I made a teacher information card, where the teacher could see his teacher information, I also made the home page where to display this card and implemented the responsive design of these elements. And I also did some sidebar fixes.

#### Extras
*There are a lot of teachers'cards just to show and test the responsive design
![image](https://github.com/javonunezz/teacher_book_front/assets/62576531/321aa684-b22f-4358-93fc-51058d1c90e4)
![image](https://github.com/javonunezz/teacher_book_front/assets/62576531/6164a377-b16c-4526-9ce1-5a2a9dc9234f)
![image](https://github.com/javonunezz/teacher_book_front/assets/62576531/9320cdad-5473-44c7-8bd1-353049d72479)

2023-05-14 22:29 UTC, yurehn requested changes

2023-05-14 22:29 UTC, yurehn commented on src/components/Organisms/Pages/Home/CardTeacher.jsx
Agregar el name a infoTeacher

2023-05-14 22:29 UTC, yurehn commented on src/assets/chancho.jpg
revisar si las imágenes van en src/assets o en public

2023-05-14 22:40 UTC, javonunezz commented on src/assets/chancho.jpg
My sweet friend, you don't know anything about where to put the images of the project.

2023-05-14 22:49 UTC, javonunezz commented on src/components/Organisms/Pages/Home/CardTeacher.jsx
Ready!!, my sweet friend

2023-05-14 22:53 UTC, yurehn approved these changes

2023-05-15 16:59 UTC, alegrimminck commented on src/App.jsx
Nice work! I have some little comments here:
- I started using large media query "lg:" instead of "md:" because it works better in responsive mode in some cases, maybe we could use "lg:" everywhere?
- I was thinking that the `PageMainHome` component could be divided into a generic parent for the content and the "MainHome" component, why? because there's a lot of views where we need the exact same padding for the content at the right of the sidebar, so instead of repeating those tailwind classes we could do something like: 
```jsx 
<MainContent>
  <Home>
</MainContent>
```
And then only change the "Home" for "Courses" for example

2023-05-15 17:06 UTC, alegrimminck commented on src/components/Organisms/Pages/Home/CardTeacher.jsx
This component was neatly structured! There's only a few details with the inconsistent use of language, since we should do everything in english, you could change:
- "imagen" import to "image"
- "The name_teacher, subject_teacher and email keys of `infoTeacher` have spanish words
- The alt property in line 18 has spanish names

2023-05-15 17:06 UTC, alegrimminck commented on src/assets/chancho.jpg
Love the monkey lol, just the name "chancho" could be changed to "pig"

2023-05-15 19:47 UTC, javonunezz commented on src/App.jsx
Good point!, I made the changes you said.

2023-05-15 19:47 UTC, javonunezz commented on src/assets/chancho.jpg
I changed the name and the image.

2023-05-15 19:47 UTC, javonunezz commented on src/components/Organisms/Pages/Home/CardTeacher.jsx
changed the name of "imagen" to "image".
changed the data in infoteacher
changed the name in line 18

2023-05-15 19:53 UTC, alegrimminck approved these changes
Nice, I think it's ready now! I approved it

2023-05-16 19:15 UTC, merged